# Generated by Django 3.0.2 on 2020-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='toDoList',
            new_name='todolist',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
